name: Publish Templates
on:
  push:
    branches:
      - main
jobs:
  publish_template:
    name: Publish Template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install npm Dependencies
        run: npm install

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Publish template
        run: npm run update-templates ${{ steps.changed-files.outputs.all_changed_files }}
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
          CONTENTFUL_CONTENT_TYPE: ${{ secrets.CONTENTFUL_CONTENT_TYPE }}
